# name of the workflow
name: Pytest

on:
  # trigger 1: pushing to the master branch
  push:
    branches: [ "master" ]
  # trigger 2: opening a pull request to the master branch
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# the job and the contained steps will be executed whenever a trigger occurs
jobs:
  # name of the job
  test:
    # environment, in which the job will be executed
    runs-on: ubuntu-latest

    steps:
      # Checkout the code onto the runner
      - uses: actions/checkout@v3
      # Setup Python on the runner
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      # Install the dependencies and libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.pip
      # Execute unit tests
      - name: unit tests
        run: |
          python -m pytest -m unit


